services:
  php:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - db
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony_network
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - symfony_network
    depends_on:
      - db
networks:
  symfony_network:
    driver: bridge
volumes:
  db_data:
  caddy_data:
  caddy_config:
